baseURL: 'https://staging.alexrampp.de/'
languageCode: en-us
defaultContentLanguage: en
title: Alex's Personal Web Site
theme: PaperMod
enableEmoji: true
enableRobotsTXT: true

params:
  homeInfoParams:
    Title: Hi there
    Content: Welcome to my personal web site!
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: false

  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/bitschupser"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/alexander-rampp-422834204/"
    - name: "dev"
      url: "https://dev.to/bitschupser"
    - name: "github"
      url: "github.com/bitSchupser/"

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    category: categories
    tag: tags

permalinks:
  posts: '/:year/:month/:title/'

menu:
  main:
    - identifier: articles
      pre: ''
      post: ''
      name: Articles
      url: /articles/
      title: ''
      weight: 1
    - identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 2
    # - identifier: categories
    #   pre: ''
    #   post: ''
    #   name: Categories
    #   url: /categories/
    #   title: ''
    #   weight: 3
    - identifier: search
      pre: ''
      post: ''
      name: Search
      url: /search/
      title: ''
      weight: 4
    - identifier: archives
      pre: ''
      post: ''
      name: Archive
      url: /archives/
      title: ''
      weight: 5
    - identifier: about
      pre: ''
      post: ''
      name: About
      url: /about/
      title: ''
      weight: 6

markup:
  highlight:
    noClasses: false

