baseURL: 'https://staging.alexrampp.de/'
languageCode: en-us
defaultContentLanguage: en
title: Alex's personal homepage
theme: PaperMod
enableEmoji: true
enableRobotsTXT: true

params:
  homeInfoParams:
    Title: Hi there
    Content: >
      Welcome to my personal web site!<br/>

  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/bitschupser"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/alexander-rampp-422834204/"
    - name: "dev"
      url: "https://dev.to/bitschupser"
    - name: "github"
      url: "github.com/bitSchupser/"

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    category: categories
    tag: tags

permalinks:
  posts: '/:year/:month/:title/'

menu:
  main:
    - identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
      weight: 1
    - identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 2
    # - identifier: categories
    #   pre: ''
    #   post: ''
    #   name: Categories
    #   url: /categories/
    #   title: ''
    #   weight: 3
    - identifier: archives
      pre: ''
      post: ''
      name: Archive
      url: /archives/
      title: ''
      weight: 4

markup:
  highlight:
    noClasses: false

